<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="..\FauxCore\FauxCommon\Common.targets" />
	<Import Project="..\FauxCore\FauxCommon\FauxCommon.projitems" Label="Shared" />

	<PropertyGroup>
		<Name>Unlimited Storage Tests</Name>
		<Description>Automated tests for Unlimited Storage</Description>
		<Version>1.0.0</Version>
		<EnableHarmony>true</EnableHarmony>
		<RootNamespace>LeFauxMods.UnlimitedStorage.Test</RootNamespace>
		<UniqueId>furyx639.UnlimitedStorageTest</UniqueId>
		<RepositoryUrl>https://github.com/LeFauxMatt/UnlimitedStorage</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<EnableModZip>False</EnableModZip>
	</PropertyGroup>

	<ItemGroup>
		<SMAPIDependency Include="furyx639.FauxCore" Version="2.0.0" required="true" />
		<SMAPIDependency Include="spacechase0.GenericModConfigMenu" Version="1.14.1" required="false" />
	</ItemGroup>

</Project>